/*
 *     Copyright (c) 2025 Adrian & Frank Buehlmann. ALL RIGHTS RESERVED.
 */

module;

#include "d1/d1assert.h"

export module Core.Shift;

import Core.Main;

import d1.ListSet;
import d1.Point;
import d1.round;


namespace Core
{

export class IShiftable;


export class ShiftVector // has value semantics
{
public:
    d1::fVector distance = {};
    // The distance a shiftable object should shift relative to its old position
    // (old = the position before the transaction started).

    bool shiftX = true; // A shiftable object should not change the x part of its
                        // position if shiftX is false.

    bool shiftY = true; // A shiftable object should not change the y part of its
                        // position if shiftY is false.

    ShiftVector() {}

    ShiftVector(const d1::fVector& distance):
        distance{ distance }
    {
    }

    bool isNull() const { return not shiftX and not shiftY; }
    // Note: distance == (0,0) means not that a ShiftVector is null!

    d1::fPoint getNewPos(
        const d1::fPoint& actpos, const d1::fPoint& oldpos) const;

    d1::Point getNewPos(
        const d1::Point& actpos, const d1::Point& oldpos) const;
};


inline d1::fPoint ShiftVector::getNewPos(
    const d1::fPoint& actpos, const d1::fPoint& oldpos) const
{
    return {
        shiftX ? oldpos.x + distance.dx : actpos.x,
        shiftY ? oldpos.y + distance.dy : actpos.y
    };
}


inline d1::Point ShiftVector::getNewPos(
    const d1::Point& actpos, const d1::Point& oldpos) const
{
    return {
        shiftX ? oldpos.x + d1::round(distance.dx) : actpos.x,
        shiftY ? oldpos.y + d1::round(distance.dy) : actpos.y
    };
}


export class ShiftSet
{
    using Shiftables = d1::ListSet<IShiftable*>;
    using Dependents = d1::ListSet<std::pair<
        IShiftable* /*sender*/, IShiftable* /*dependent*/>>;


    ShiftVector actualShiftVector_;
    d1::fPoint actualMousePos_;
    IShiftable* masterMover_ = nullptr; // may be zero
    IShiftable* actualSender_ = nullptr;
    Shiftables instantShiftables_, deferredShiftables_;
    Dependents dependents_;

public:
    ShiftSet();
    ShiftSet(const ElementSet& selection, IDiagram&,
        IShiftable* theMasterMover = 0);

    ShiftSet(const ShiftSet&) = delete;
    ShiftSet& operator=(const ShiftSet&) = delete;


    void deferredShift(Env&, const ShiftVector&, const d1::fPoint& mouse_pos);
    void finalShift(Env&);

    auto getDeferredShift() const -> const ShiftVector&;


    void addNormal(IShiftable&);

    auto getMasterMover() const -> IShiftable* { return masterMover_; }


    void addNormalSet(const auto& container)
    {
        for (auto* s : container)
            addNormal(*s);
    }

    void addDependent(IShiftable&);

    void addDependentSet(const auto& container)
    {
        for (auto* s : container)
            addDependent(*s);
    }

    template <class Iter>
    void addDependentSet(Iter a, Iter b)
    {
        for (; a != b; ++a)
            addDependent(**a);
    }

    bool isDeferredShifting(const IShiftable&) const;

    auto begin() const { return deferredShiftables_.begin(); }
    auto end() const { return deferredShiftables_.end(); }

    void print(std::ostream&) const; // for debugging

    friend std::ostream& operator<<(std::ostream& s, const ShiftSet& d)
    {
        d.print(s);
        return s;
    }
};


export class IShiftable: public virtual IElement
{
public:
    IShiftable() {}
    //  IShiftable(const IShiftable&)   generated by compiler

    IShiftable& operator=(const IShiftable&) = delete;

    void shift(Env&,
        IElement* sender,
        const ShiftVector&,
        const ShiftSet&,
        bool shallow);

    virtual void shiftImpl(Env&,
        IElement* sender,
        const ShiftVector&,
        const ShiftSet&,
        bool shallow) = 0;

    virtual void addNormal(ShiftSet&, const ElementSet& selection) = 0;
    virtual void addDependents(ShiftSet&) = 0;

    virtual void detachFromSource(Env&,
        const ShiftSet&, const ElementSet& selection);

    virtual void extendSelection(
        const ElementSet& selection,
        ElementSet& extendedSelectionSet);
};


export class ActorAddDeferredShiftDependent
{
    ShiftSet& dss;

public:
    ActorAddDeferredShiftDependent(ShiftSet& dss):
        dss{ dss }
    {
    }

    void operator()(IShiftable* t)
    {
        dss.addDependent(*t);
    }
};

}

module :private;

namespace Core
{

void IShiftable::shift(Env& e,
    IElement* sender,
    const ShiftVector& sv,
    const ShiftSet& dss,
    bool shallow)
{
    if (isInTrash())
        return;

    if (dss.isDeferredShifting(*this))
        return;

    shiftImpl(e, sender, sv, dss, shallow);
}


void IShiftable::detachFromSource(Env&,
    const ShiftSet&, const ElementSet& selection)
{
    // default: nothing to detach
}


void IShiftable::extendSelection(const ElementSet&, ElementSet&)
{
}


ShiftSet::ShiftSet()
{
    actualShiftVector_.shiftX = false;
    actualShiftVector_.shiftY = false;
}


ShiftSet::ShiftSet(
    const ElementSet& selection,
    IDiagram& d,
    IShiftable* theMasterMover):

    masterMover_{ theMasterMover }
{
    actualShiftVector_.shiftX = false;
    actualShiftVector_.shiftY = false;

    for (auto me : d)
    {
        D1_ASSERT(me);
        if (auto s = dynamic_cast<IShiftable*>(me))
            s->addNormal(*this, selection);
    }

    for (auto ds : deferredShiftables_)
    {
        actualSender_ = ds;
        actualSender_->addDependents(*this);
    }

    for (auto me : selection)
    {
        D1_ASSERT(me);
        auto s = dynamic_cast<IShiftable*>(me.get());
        if (s and not isDeferredShifting(*s))
            instantShiftables_.insert(s);
    }

    actualSender_ = 0;
}


void ShiftSet::deferredShift(
    Env& e, const ShiftVector& sv, const d1::fPoint& mouse_pos)
{
    actualShiftVector_ = sv;
    actualMousePos_ = mouse_pos;

    for (auto is : instantShiftables_)
        is->shift(e, 0, sv, *this, false /*not shallow*/);

    for (auto& d : dependents_)
        d.second->shiftImpl(e, d.first, sv, *this, false /*not shallow*/);
}


void ShiftSet::finalShift(Env& e)
{
    for (auto s : deferredShiftables_)
        s->shiftImpl(e, 0, actualShiftVector_, *this, true /*shallow*/);
}


auto ShiftSet::getDeferredShift() const -> const ShiftVector&
{
    return actualShiftVector_;
}


void ShiftSet::addNormal(IShiftable& s)
{
    deferredShiftables_.insert(&s);
}


void ShiftSet::addDependent(IShiftable& s)
{
    D1_ASSERT(&s);
    if (not isDeferredShifting(s))
        dependents_.insert(std::pair{ actualSender_, &s });
}


bool ShiftSet::isDeferredShifting(const IShiftable& s) const
{
    return deferredShiftables_.find(const_cast<IShiftable*>(&s)) != deferredShiftables_.end();
}


void ShiftSet::print(std::ostream& os) const
{
#ifdef _DEBUG
    Core::printSortedIDs(os, deferredShiftables_);
#endif
}

}
